### ISSUE TITLE
ActiveRecord enum attribute with i18n translation doesn't work?

### ISSUE THREAD

**Issue by oni7uka** [formtastic/formtastic#1286]
I'm reading the document from https://github.com/justinfrench/formtastic/blob/f94423144eee14ccc03a64267fcafd583d3cdf85/lib/formtastic/inputs/radio_input.rb#L107
But it doesn't work.
This is my **form code:**
`  f.input :position, :as => radio `
**model:**
```
enum position: {LT: 1, CT: 2, RT: 3, 
                  LM: 4, CM: 5, RM: 6,
                  LB: 7, CB: 8, RB: 9}
```
**i18n file:**
```
zh-CN:
  activerecord:
    attributes:
      watermark:
        positions:
          one: 位置
          LT: 左上
          CT: 中上
          RT: 右上
          LM: 左中
          CM: 正中
          RM: 右中
          LB: 左下
          CB: 中下
          RB: 右下
```
Am I missing something?  My formtastic version is 3.1.5
